name: 'Publicar actualización'

on:
  push:
    branches:
      - release

jobs:
  publish-tauri:
    permissions:
      contents: write

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: install frontend dependencies
        run: npm install

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        with:
          tagName: 'v__VERSION__'
          releaseName: 'Presupuestos A.M.W. v__VERSION__'
          releaseBody: 'Nueva versión de la app.'
          releaseDraft: true
          prerelease: false
